DROP DATABASE IF EXISTS qh;

CREATE DATABASE IF NOT EXISTS qh;

USE qh;

CREATE TABLE IF NOT EXISTS qh (
    userId INT UNSIGNED NOT NULL AUTO_INCREMENT,
    login VARCHAR(40) NOT NULL,
    password VARCHAR(40) NOT NULL,
    PRIMARY KEY (userId)
);